USE Minions
GO
CREATE TABLE Minions (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(30) NOT NULL,
	Age INT 
)

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(50) NOT NULL
)

