CREATE TABLE Users(
	Id BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Username VARCHAR(30) UNIQUE NOT NULL,
	Password VARCHAR(26) NOT NULL,
	ProfilePicture VARBINARY(MAX),
	LastLoginTime DATETIME,
	IsDeleted BIT,
	CONSTRAINT CHK_ProfilePictureSize CHECK (DATALENGTH(ProfilePicture)<=900*1024) 
)

INSERT INTO Users 
VALUES
('Userv','123455',NULL,NULL,NULL),
('RosenTraykov','123455',NULL,NULL,NULL),
('IlianaAngelova','123455',NULL,NULL,NULL),
('DarinAngelov','123455',NULL,NULL,NULL),
('StefanDimitrov','123455',NULL,NULL,NULL),
('IvanGeorgiev','123455',NULL,NULL,NULL)

GO

ALTER TABLE Users 
DROP CONSTRAINT [PK__Users__3214EC07FBE7C975]

GO

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (Id,Username)

GO

ALTER TABLE Users
ADD CONSTRAINT CHK_PasswordSize CHECK (DATALENGTH(Password)>=5)

GO

ALTER TABLE Users
ADD DEFAULT GETDATE()
FOR LastLoginTime